name: Java CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4  # Upgraded to v4

      # Step 2: Set up JDK 21 (matches pom.xml)
      - name: Set up JDK 21
        uses: actions/setup-java@v4  # Upgraded to v4
        with:
          distribution: 'temurin'
          java-version: '21'

      # Step 3: Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      # Step 4: Build and test in one step
      - name: Build and Test
        run: mvn clean test  # Runs JUnit tests

      # Step 5: Upload test reports
      - name: Upload Test Reports
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: surefire-reports
          path: target/surefire-reports/
